# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

# gruvbox-dark palette adapted from:
#   https://github.com/morhetz/gruvbox
gui:
  authorColors:
    '*': '#d3869b'

  border: rounded

  theme:
    activeBorderColor:
      - '#d3869b'
      - bold
    inactiveBorderColor:
      - '#bdae93'
    optionsTextColor:
      - '#83a598'
    selectedLineBgColor:
      - '#3c3836'
    cherryPickedCommitBgColor:
      - '#504945'
    cherryPickedCommitFgColor:
      - '#d3869b'
    unstagedChangesColor:
      - '#fb4934'
    defaultFgColor:
      - '#fbf1c7'
    searchingActiveBorderColor:
      - '#fabd2f'
