[act3]
apt-pkg = ""
arch-pkg = ""
brew-is-cask = false
brew-supports-darwin = false
brew-supports-linux = false
brew-tap = "dhth/tap"
description = "TODO: Add description for act3"
fedora-pkg = ""
flatpak-pkg = ""
prefer_flatpak = false
priority = ""

["python@3.11"]
apt-pkg = ""
arch-pkg = ""
brew-is-cask = false
brew-supports-darwin = true
brew-supports-linux = true
brew-tap = ""
description = "TODO: Add description for python@3.11"
fedora-pkg = ""
flatpak-pkg = ""
prefer_flatpak = false
priority = ""

