#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    powerline_symbol = ''
    leading_diamond = ''
    template = '{{.Icon}} '
    background = 'p:blue'
    foreground = 'p:wight'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    powerline_symbol = ''
    template = '{{ .UserName }}@{{ .HostName }}'
    background = 'p:blue'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .Path }}'
    background = 'p:pink'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .HEAD }}'
    background = 'p:lavender'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[palette]
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  os = '#ACB0BE'
  pink = '#F5BDE6'
  text = '#494D64'
  wight = '#FFFFFF'
